# Generated by Django 6.0.4 on 2026-04-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveDate',
        ),
    ]
