# Generated by Django 6.0.4 on 2026-05-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_usermessage_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(blank=True, help_text='Detailed address with landmarks'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location_coords',
            field=models.TextField(blank=True, help_text='GPS coordinates (lat,lng)'),
        ),
    ]
